export default {
  SET_QUESTIONS: "SET_QUESTIONS",
  SET_SCORE: "SET_SCORE",
  SET_SHOW_SCORE: "SET_SHOW_SCORE",
  IS_PLAY: "IS_PLAY",
  SET_INIT_SCORE: "SET_INIT_SCORE",
  SET_HIGHSCORE: "SET_HIGHSCORE",
  SET_COUNTER: "SET_COUNTER",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
};
